#ifndef MATRIX_FUNCTIONS
#define MATRIX_FUNCTIONS
constexpr int ARRAYSIZE = 2;
void buildQR(double A[ARRAYSIZE][ARRAYSIZE], double Q[ARRAYSIZE][ARRAYSIZE], double R[ARRAYSIZE][ARRAYSIZE]);
void buildDynamicMatrix(double K[ARRAYSIZE][ARRAYSIZE], double M[ARRAYSIZE][ARRAYSIZE], double D[ARRAYSIZE][ARRAYSIZE]);
#endif // MATRIX_FUNCTIONS 
